plugins:
#  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 4 versions
#    - Safari > 2
safe: false
future: true
baseurl: "/dsa2024nyeri_demo"
url: "http://www.datascienceafrica.org"
title: "Data Science Africa Nyeri 2024"
email: "info@datascienceafrica.org"
description: "DSA 2024, NYERI"
googleAnalyticsTrackingId: "UA-80484960-1"
googleAnalyticsSiteUrl: "datascienceafrica.org"
venuName: "Dedan Kimathi University of Technology, Nyeri"
venuLogo: "University-of-Rwanda-LOGO-B-_RV.png"
sitetheme: "Data Science for Social Good in the Age of Generative AI"
dates: "3<sup>rd</sup> - 7<sup>th</sup> June 2024"


# Speakers List Block
showSessions: true

# Head
metaKeywords: "event, data science, africa, dsa, programming, machine learning, developers"
twitterAccount: "@dsa_org"

# Documents
c4pUrl: ""
c4sponsorsUrl: "mailto:info@datascienceafrica.org?subject=Event%20Sponsorship%20for%20DSA%202024%20Nyeri"

# Highlights Block
aboutTitle: "Highlights"
aboutBlock:
 - {id: 1, title: "Generative AI", image: "Picture2-02.jpg", text: "Unleash the power of Generative AI in this intensive three-day summer school from Monday to Wednesday. This program goes beyond basic creation, allowing you to explore the inner workings of these fascinating models. Delve into Deep Generative AI, unravelling the secrets behind image, text, and code generation. You will have the opportunity to get hands-on experience in practicum labs, where you can build your own generative systems. Don't miss this chance to become a master of AI creation! " }
 - {id: 2, title: "Natural Language Processing", image: "Picture2-03.jpg", text: "This summer school offers an intensive dive into the world of Natural Language Processing (NLP) for African languages!  Over three days (Monday to Wednesday), you will explore the power of Large Language Models (LLMs), focusing on real-world applications for East Africa.  Develop an AI-powered agricultural assistant, tackle speech recognition for under-resourced languages, and delve into end-to-end speech technology.  Get hands-on experience building your own AI systems through practicum labs, and gain the skills to unlock the potential of NLP for African languages –  are you ready to be a language AI pioneer? " }
 - {id: 3, title: "Edge AI", image: "Picture2-01.jpg", text: "We will take you on an exhilarating journey into the heart of Edge AI – where intelligence meets the real world.  Forget bulky servers! Here, you will build and deploy Machine Learning models directly onto tiny devices like Raspberry Pis.  Witness the magic firsthand as your creation analyzes bioacoustic data in the field, providing real-time insights into the hidden symphony of nature.  Imagine the 'wow' factor of seeing your AI model identify bird calls or track animal movements – all thanks to your own ingenuity and a pocket-sized powerhouse.  This is more than just learning – it's about pushing the boundaries of AI and making a tangible impact on the environment.
" }
 
# Latest News Block
latestNewsTitle: "Latest news"