plugins:
#  - jekyll-autoprefixer

autoprefixer:
  browsers:
    - last 4 versions
#    - Safari > 2
safe: false
future: true
baseurl: "/dsa2024nyeri_demo"
url: "http://www.datascienceafrica.org"
title: "Data Science Africa Nyeri 2024"
email: "info@datascienceafrica.org"
description: "DSA 2024, NYERI"
googleAnalyticsTrackingId: "UA-80484960-1"
googleAnalyticsSiteUrl: "datascienceafrica.org"
venuName: "Dedan Kimathi University of Technology, Nyeri"
venuLogo: "University-of-Rwanda-LOGO-B-_RV.png"
sitetheme: "GeoAI4Good: Harnessing the Transformative Power of AI Foundation Models for Earth Observation for Environmental Monitoring"
dates: "3<sup>rd</sup> - 7<sup>th</sup> June 2024"


# Speakers List Block
showSessions: true

# Head
metaKeywords: "event, data science, africa, dsa, programming, machine learning, developers"
twitterAccount: "@dsa_org"

# Documents
c4pUrl: ""
c4sponsorsUrl: "mailto:info@datascienceafrica.org?subject=Event%20Sponsorship%20for%20DSA%202024%20Nyeri"

# Highlights Block
aboutTitle: "Highlights"
aboutBlock:
 - {title: "Embedded ML - Tiny ML", image: "TinyML_2022.jpg", text: "TinyML is a cutting-edge field that brings the transformative power of machine learning (ML) to the performance- and power-constrained domain of tiny devices and embedded systems. Successful deployment in this field requires intimate knowledge of applications, algorithms, hardware, and software." }
 - {title: "Summer School", image: "summer_school.jpg", text: "In the tradition of previous Data Science Africa  events, a summer school on machine learning and data science will be held prior to the main workshop. This summer school will target graduate students, researchers, and professionals working with huge amounts of data or unique datasets. The summer school will focus on introductory and advanced lectures in data science and machine learning as well as moderate to advanced practical and tutorial sessions where participants will get their hands wet wrangling and munging datasets and apply cutting edge machine learning techniques to derive inference from the data.
" }
 - {title: "Workshop", image: "Workshop_2022.jpg", text: "The workshop will be organized around paper presentations and interactive panel discussions. The theme for the workshop is Data, Technology, and Community. We want to highlight the work of the community in Data Science in Africa. We strongly encourage the participation of researchers and data science communities from across the continent. We invite participants interested in presenting work at the workshop to submit a short abstract describing the application of data science methods to problems relevant to Africa." }
 
# Latest News Block
latestNewsTitle: "Latest news"